PIPAFU/PIPAFU/Controllers/MeusCursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PIPAFU.Data;
using PIPAFU.Exceptions;
using PIPAFU.Models;

namespace PIPAFU.Controllers
{
    [Authorize]
    public class MeusCursosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;


        public MeusCursosController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: MeusCursos
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var applicationDbContext = _context.Curso.Include(c => c.Professor)
                .Where(x => x.ApplicationUserId == userId);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: MeusCursos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Curso
                .Include(c => c.Professor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // GET: MeusCursos/Create
        public IActionResult Create()
        {
            ViewData["Professor"] = _userManager.GetUserId(User);
            return View();
        }

        // POST: MeusCursos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Data,Descricao,ApplicationUserId")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                curso.Data = DateTime.Now;
                _context.Add(curso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(curso);
        }

        // GET: MeusCursos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Curso.FindAsync(id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        // POST: MeusCursos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Data,Descricao,ApplicationUserId")] Curso curso)
        {
            if (id != curso.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(curso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursoExists(curso.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        // GET: MeusCursos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Curso
                .Include(c => c.Professor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        // POST: MeusCursos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var curso = await _context.Curso.FindAsync(id);
                _context.Curso.Remove(curso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException e)
            {
                throw new IntegrityException("Não pode deletar o curso porque ele possui videos");
            }
        }

        private bool CursoExists(int id)
        {
            return _context.Curso.Any(e => e.Id == id);
        }
    }
}

PIPAFU/PIPAFU/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PIPAFU.Data;
using PIPAFU.Models;
using PIPAFU.Models.ViewModels;
using PIPAFU.Services;
using VimeoDotNet;
using VimeoDotNet.Net;

namespace PIPAFU.Controllers
{
    public class VideosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly VimeoApiService _vimeoApiService;

        public VideosController(ApplicationDbContext context, VimeoApiService vimeoApiService)
        {
            _context = context;
            _vimeoApiService = vimeoApiService;
        }

        // GET: Videos
        public async Task<IActionResult> Index(int? cursoId, bool? editar = false)
        {
            ViewData["Editar"] = editar;
            var videos = await _context.Video.Where(v => v.Curso.Id == cursoId).ToListAsync();
            ViewData["cursoId"] = cursoId;
            ViewData["nomeCurso"] = _context.Curso.Where(c => c.Id == cursoId).Select(c => c.Nome).FirstOrDefault();
            return View(videos);
        }

        public async Task<IActionResult> Video(int? clipId, int cursoId)
        {
            var videoEscolhido = await _context.Video.Where(v => v.ClipId == clipId.Value).FirstOrDefaultAsync();
            var videos = await _context.Video.Where(v => v.Curso.Id == cursoId).ToListAsync();
            var curso = await _context.Curso.Where(c => c.Id == cursoId).FirstOrDefaultAsync();

            var videoViewModel = new VideoViewModel { Video = videoEscolhido, Videos = videos, Curso = curso };

            return View(videoViewModel);
        }

        // GET: Videos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _context.Video
                .FirstOrDefaultAsync(m => m.Id == id);
            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

        // GET: Videos/Create
        //[DisableRequestSizeLimit]
        [DisableRequestSizeLimit, RequestFormLimits(MultipartBodyLengthLimit = Int32.MaxValue, ValueLengthLimit = Int32.MaxValue)]
        public async Task<IActionResult> Create(int? cursoId)
        {
            var curso = await _context.Curso.Where(c => c.Id == cursoId.Value).FirstOrDefaultAsync();
            var viewModel = new VideoViewModel { Curso = curso };
            return View(viewModel);
        }

        // POST: Videos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[DisableRequestSizeLimit]
        [DisableRequestSizeLimit, RequestFormLimits(MultipartBodyLengthLimit = Int32.MaxValue, ValueLengthLimit = Int32.MaxValue)]
        public async Task<IActionResult> Create(Video video)
        {
            var files = Request.Form.Files;
            IFormFile file = files[0];

            if (ModelState.IsValid)
            {
                video = await _vimeoApiService.UploadVimeoAsync(file, video);
                video.Data = DateTime.Now;
                _context.Add(video);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { cursoId = video.CursoId, editar = true });
            }
            return View(video);
        }

        // GET: Videos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _context.Video.FindAsync(id);
            if (video == null)
            {
                return NotFound();
            }
            return View(video);
        }

        // POST: Videos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ChunkSize,BytesWritten,IsVerifiedComplete,ClipUri,FileLength,ClipId")] Video video)
        {
            if (id != video.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(video);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VideoExists(video.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(video);
        }

        // GET: Videos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _context.Video
                .FirstOrDefaultAsync(m => m.Id == id);
            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

        // POST: Videos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var video = await _context.Video.FindAsync(id);
            await _vimeoApiService.DeleteVideo(video.ClipId);
            _context.Video.Remove(video);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VideoExists(int id)
        {
            return _context.Video.Any(e => e.Id == id);
        }
    }
}

PIPAFU/PIPAFU/Views/MeusCursos/Create.cshtml
@model PIPAFU.Models.Curso

@{
    ViewData["Title"] = "Criar Curso";
}

<h1>@ViewData["Title"]</h1>

@*<h4>Curso</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                @*<input asp-for="Descricao" class="form-control" />*@
                <textarea asp-for="Descricao" class="form-control" type="text"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <input asp-for="ApplicationUserId" value="@ViewData["Professor"]" class="form-control" hidden /> <!--Add criador do curso-->
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>

        <div>
            <a asp-action="Index" class="btn btn-secondary">Voltar para a lista</a>
        </div>

    </div>
    <div class="col-md-1"></div>
    <div class="col-md-6 col-md-offset-2">
        <section>
            <img src="~/Arquivos/icone-video-laranja.png" alt="Tablet" class="embed-responsive"/>
        </section>
    </div>
</div>

@section Scripts { <!--não sei se precisa-->
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PIPAFU/PIPAFU/Views/MeusCursos/Delete.cshtml
@model PIPAFU.Models.Curso

@{
    ViewData["Title"] = "Apagar Curso";
}

<h1>@ViewData["Title"]</h1>

<h3>Tem certeza que deseja apagar o curso: @Model.Nome?</h3>
<div>
    @*<h4>Curso</h4>*@
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Professor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Professor.Id)
        </dd class>*@
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Voltar para a lista</a>
    </form>
</div>

PIPAFU/PIPAFU/Views/MeusCursos/Details.cshtml
@model PIPAFU.Models.Curso

@{
    ViewData["Title"] = "Detalhes do Curso";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>@Model.Nome</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Professor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Professor.UserName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a>
    <a asp-action="Index" class="btn btn-secondary">Voltar para a lista</a>
</div>

PIPAFU/PIPAFU/Views/MeusCursos/Edit.cshtml
@model PIPAFU.Models.Curso

@{
    ViewData["Title"] = "Editar Curso";
}

<h1>Editar Curso</h1>

<h4>@Model.Nome</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ApplicationUserId" /> <!--Mantém valor da FK-->
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="Data" class="control-label"></label>
                    <input asp-for="Data" class="form-control" />
                    <span asp-validation-for="Data" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                @*<input asp-for="Descricao" class="form-control" />*@
                <textarea asp-for="Descricao" class="form-control" type="text"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="Index" class="btn btn-secondary" >Voltar para a lista</a>
        </div>

    </div>
    <div class="col-md-1"></div>
    <div class="col-md-6 col-md-offset-2">
        <section>
            <img src="~/Arquivos/icone-video-laranja.png" alt="Tablet" class="embed-responsive" />
        </section>
    </div>
</div>

@section Scripts { <!--não sei se precisa-->
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PIPAFU/PIPAFU/Views/MeusCursos/Index.cshtml
@model IEnumerable<PIPAFU.Models.Curso>

@{
    ViewData["Title"] = "Meus Cursos";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create" class="btn btn-secondary">Novo Curso</a>
</p>
<table class="table table-striped table-hover">
    <thead>
        <tr class="table-active">
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Professor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Professor.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Index", "Videos", new { cursoId = item.Id, editar = true })" class="btn btn-outline-primary">@Html.DisplayFor(modelItem => item.Nome)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Professor.NomeUsuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Professor.Email)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">Editar</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary">Detalhar</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-secondary">Apagar</a>
                </td>
            </tr>
        }
    </tbody>
</table>